modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/PixilareGames/ThriveCraft/issues"

[[mods]] #mandatory
	modId="thrivecraft"
	version="1.0"
	displayName="Thrive Craft"
	updateJSONURL="https://github.com/PixilareGames/ThriveCraft/tree/master/1.14/1.14.4"
	displayURL="https://github.com/PixilareGames/ThriveCraft"
	logoFile="thrivecraft.png"
	credits="Herobrain_gamer For Coding, GamerGabriel For Textures, TheTrueDuility For Helping"
	authors="Herobrain_gamer, GamerGabriel, TheTrueDuility"
	description='''Ian Please Add More Information'''

[[dependencies.thrivecraft]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.thrivecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.thrivecraft]]
    modId="pixelcore"
    mandatory=true
    versionRange="[1.0]"
    ordering="NONE"
    side="BOTH"