modLoader="javafml"
loaderVersion="[24,)"
credits="Herobrain_gamer_Coding,GamerGabriel_Textures,TheTrueDuility_SlaveDrivingAss"
authors="Herobrain_gamer,GamerGabriel,TheTrueDuility"

[[mods]] #mandatory
modId="thrivecraft"
version="0.1"
displayName="Thrive Craft"
description='''
This is a mod that adds a bunch of stuff
like mobs, blocks, items, ore, armor, bosses ect
This mod is awesome as rated by no-one
'''

[[dependencies.thrivecraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.thrivecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"